name: Build Redmi 4X (Santoni) Images

on:
  push:
  workflow_dispatch:
  
jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
         
         sudo apt-get install -y git gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu make bc bison flex libssl-dev libelf-dev qemu-user-static python-is-python3 python3-venv python3-pip

      - name: Clone pmbootstrap
        run: |
          git clone https://gitlab.com/postmarketOS/pmbootstrap.git -b 2.3.0 pmbs && sudo ln -s "$(pwd)/pmbs/pmbootstrap.py" /usr/bin/pmbootstrap 
    
      - name: Create and activate virtual environment
        run: |
          # Membuat lingkungan virtual
          mkdir -p /home/runner/.config
          mkdir -p /home/runner/.local/var/pmbootstrap

      - name: Initialize pmbootstrap for Redmi 4X (Santoni)
        run: |
          # Menginisialisasi konfigurasi untuk Redmi 4X (Santoni)
          #echo -e "$HOME/.local/var/pmbootstrap\nedge\nxiaomi\nsantoni\npantheon" | pmbootstrap init
          #pmbootstrap install
          sudo mv pmbootstrap.cfg /home/runner/.config/pmbootstrap_v3.cfg
           sudo chmod 777 /home/runner/.config/pmbootstrap_v3.cfg
           pmbootstrap -c /home/runner/.config/pmbootstrap_v3.cfg -y init
           pmbootstrap install --password root
           pmbootstrap export
          mv /tmp/postmarketOS-export/pmos-*.zip redmi-4x-santoni-flashable.zip

      - name: Upload flashable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: redmi-4x-santoni-flashable-zip
          path: redmi-4x-santoni-flashable.zip
          retention-days: 7
