name: Build Redmi 4X (Santoni) Images

on:
  push:
  workflow_dispatch:
  
jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
         pwd
         ls /home
         ls -lha /home
         sudo apt-get install -y git gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu make bc bison flex libssl-dev libelf-dev qemu-user-static python3-venv python3-pip

      - name: Clone pmbootstrap
        run: |
          git clone --depth=1 https://gitlab.com/postmarketOS/pmbootstrap.git

      - name: Create and activate virtual environment
        run: |
          # Membuat lingkungan virtual
          python3 -m venv pmbootstrap-venv
          source pmbootstrap-venv/bin/activate
          HOME=$(pwd)
          # Menginstal pmbootstrap dengan pip
          cd pmbootstrap
          pip3 install tomli
          pip3 install .
          cd $HOME

      - name: Initialize pmbootstrap for Redmi 4X (Santoni)
        run: |
          # Menginisialisasi konfigurasi untuk Redmi 4X (Santoni)
          #echo -e "$HOME/.local/var/pmbootstrap\nedge\nxiaomi\nsantoni\npantheon" > .config/pmbootstrap_v3.cfg
          #pmbootstrap install
          
          # yes '' | ./pmbootstrap/pmbootstrap.py init
           mkdir -p /home/runner/.config
           sudo mv pmbootstrap.cfg /home/runner/.config/pmbootstrap_v3.cfg
           sudo chmod 777 /home/runner/.config/pmbootstrap_v3.cfg
           yes '' | ./pmbootstrap/pmbootstrap.py init
           ./pmbootstrap/pmbootstrap.py install
     
      - name: Create artifact directories
        run: |
          mkdir -p out
          mkdir -p out_raw

      - name: Export boot.img and rootfs
        run: |
          
          pmbootstrap export out_raw/
          cp -R -u -p -L out_raw/* out/ || true

          # Compress the generated images
          xz -T0 -9e -v out/*.img
          ls -la out/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: redmi-4x-santoni
          path: out/*
          retention-days: 7
